# Workflow name shown in GitHub Actions UI
name: Docker Secrets Demo


# Defines when workflow should run
on:

  # Allows manual execution from Actions tab
  workflow_dispatch:


# jobs = collection of tasks
jobs:


  # Job ID
  secrets-job:


    # GitHub creates a temporary Ubuntu Linux VM
    runs-on: ubuntu-latest


    # steps = commands executed one-by-one
    steps:


      # Step name shown in logs
      - name: Use secrets as environment variables


        # env:
        # Creates temporary environment variables
        # available ONLY inside this step
        #
        # Left side  = variable name inside shell
        # Right side = value fetched securely from GitHub Secrets
        env:


          # Demo secret
          SECRET_MSG: ${{ secrets.MY_SECRET_MESSAGE }}


          # Docker username secret
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}


          # Docker access token secret
          DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}


        # Execute shell commands
        run: |


          # Print Docker username safely
          #
          # $DOCKER_USER means:
          # "Read value from environment variable"
          echo "Docker username is: $DOCKER_USER"


          # Print ONLY the length of token
          # Never print actual secret/token value
          #
          # ${#VARIABLE}
          # means:
          # "Length of the string"
          echo "Docker token length: ${#DOCKER_PASS}"


          # Print length of demo secret safely
          echo "Secret message length: ${#SECRET_MSG}"


          # SAFER Docker login method
          #
          # Why safer?
          # Password is passed secretly via stdin
          # instead of appearing directly in command arguments
          #
          # BAD:
          # docker login -u user -p password
          #
          # GOOD:
          # echo "$DOCKER_PASS" | docker login --password-stdin
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
