# Human-friendly name shown in GitHub Actions UI
# Think of this like the title of your workflow
name: GitHub Secrets Demo


# Defines WHEN this workflow should run
on:

  # workflow_dispatch means:
  # "Allow me to run this workflow manually from GitHub Actions tab"
  workflow_dispatch:


# jobs = collection of tasks/work units
# A workflow can have one or many jobs
jobs:


  # Name/ID of this specific job
  # GitHub internally uses this identifier
  secrets-job:


    # Defines which machine GitHub should create
    # ubuntu-latest = latest Ubuntu Linux virtual machine
    #
    # Think of this like:
    # "GitHub, give me a fresh temporary Linux computer"
    runs-on: ubuntu-latest


    # steps = list of commands/actions executed one by one
    steps:


      # Step 1
      # Friendly display name shown in logs
      - name: Check if secret exists is set (safe way)


        # run = execute shell commands inside the Linux machine
        #
        # | means:
        # "Multi-line shell script starts below"
        run: |


          # if statement in shell scripting
          #
          # -n means:
          # "Check if string length is NOT zero"
          #
          # Translation:
          # "Does this secret contain any value?"
          #
          # ${{ secrets.MY_SECRET_MESSAGE }}
          # tells GitHub:
          # "Fetch the secret safely from GitHub secret vault"
          #
          # VERY IMPORTANT:
          # Secret value is injected only during runtime
          # It is NOT stored in the YAML file
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then


            # echo prints text to terminal/logs
            #
            # If secret exists → print success message
            echo "The secret is set: true"


          # else runs when condition is false
          #
          # Meaning:
          # "Secret does not exist or is empty"
          else


            # Print false message
            echo "The secret is set: false"


          # fi = closes the if block
          # ("if" spelled backwards)
          fi



      # Step 2
      # Another step inside same job
      - name: Try printing secret directly (GitHub will mask it)


        # Execute shell commands
        run: |


          # Attempt to print secret directly
          #
          # GitHub detects secret values automatically
          # and masks them in logs
          #
          # Real value:
          # hello-devops
          #
          # What logs show:
          # ***
          #
          # This prevents accidental leakage
          echo "Attempting direct print: ${{ secrets.MY_SECRET_MESSAGE }}"


          # Normal echo statement
          # Just informational text
          echo "(GitHub replaces the value with *** in the logs)"
