[web]
web-server ansible_host=34.217.53.250

[app]
app-server ansible_host=18.236.122.224

[db]
db-server ansible_host=44.255.7.230

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/malathi/.ssh/ansible-lab.pem
ansible_python_interpreter=/usr/bin/python3

[application:children]
web
app

[all_servers:children]
application
db
