apiVersion: v1
kind: Pod
metadata:
  name: config-watcher
spec:
  containers:
    - name: watcher
      image: busybox
      command:
        - sh
        - -c
        - |
          while true; do
            echo "$(date) -> $(cat /config/message)"
            sleep 5
          done
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: live-config
