[web]
web-server ansible_host=54.187.239.252

[app]
app-server ansible_host=54.202.167.177

[db]
db-server ansible_host=34.214.208.158

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/malathi/.ssh/ansible-lab.pem
ansible_python_interpreter=/usr/bin/python3

[application:children]
web
app

[all_servers:children]
application
db
