apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
    environment: testing
    team: devops
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command:
    - sh
    - -c
    - sleep 3600
